services:
  frontend:
    build:
      context: .
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    stdin_open: true
    environment:
      - NODE_ENV=development
