services:
  frontend:
    container_name: react-product-tracker
    build: .
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true      # Optional: Add if changes still aren't detected
      - NODE_ENV=development        # Ensure React runs in development mode
    volumes:
      - ./:/app
      - /app/node_modules
